version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  soup:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is named "Dockerfile"
    network_mode: "host"
    tty: true
    container_name: soup

